### ISSUE TITLE
Backfill should be only up to a specific date

### ISSUE THREAD

**Issue by seiflotfy** [axiomhq/axiom-cloudwatch-lambda#24]
We don't want users to hit their limits backfilling, so maybe we should allow backfilling only until a specific date

**Comment by a-khaledf** [comment]
I don't really get it.
what exactly are we limiting with? the creation date of log groups?. 
subscription filter only pushes new data not old data. by backfill here is subscribing old log groups to the cloudwatch lambda function

**Comment by seiflotfy** [comment]
Sorry I meant date. The reason behind that is because we don't want users to reach their ingest quote backfilling. So maybe finding a way to ingest up to a specific time?
