### ISSUE TITLE
Backfiller lambda has a default timeout which is insufficient

### ISSUE THREAD

**Issue by rschaefer-m1** [axiomhq/axiom-cloudwatch-lambda#58]
The Backfiller lambda Cloudformation template deploys the lambda with the default 3 second timeout. This is only enough time to add about 17 log groups. 

Since this Lambda is meant to be a one-shot deal which catches all existing log groups, it makes sense to expand that to a longer timeframe by specifying a `Timeout` parameter. Something around 300 seconds should be sufficient for most cases.

**Comment by schehata** [comment]
released a new version with this change (v0.8.0)
